### ISSUE TITLE
Read/Show instance should emit parse/render to valid Haskell code

### ISSUE THREAD

**Issue by alexbiehl** [haskell/time#101]
@AshleyYakeley 

- Would you accept patches?
- How would we handle this breaking change?

**Comment by simonmichael** [comment]
Here's an advantage of keeping Show instances GHC-parseable: [pretty-show](http://hackage.haskell.org/package/pretty-show) can format them nicely. I find this useful when debugging and inspecting test failures involving complex values. Currently most of mine fail to pretty-print because they contain a Day somewhere, which disables pretty-show. I'm not sure what the best workaround is. Define custom show instances for all my types so that I can wrap the problem values in double quotes ? Declare newtypes for the time types so I can customise their rendering, and translate between these and the normal types when talking to other code ?
