### ISSUE TITLE
test-unix fails on FreeBSD and MacOS

### ISSUE THREAD

**Issue by Bodigrim** [haskell/time#149]
I crafted GitHub Actions to demonstrate this: https://github.com/haskell/time/runs/1685500304?check_suite_focus=true#step:5:3201

**Comment by AshleyYakeley** [comment]
The `test-unix` suite tests two things: that `formatTime` works correctly, using GNU `strftime` as a reference, and that `getTimeZone` respects the `TZ` environment variable. These things don't exist on Windows, which is why they're in a separate suite.

It looks like the failures are caused by `strftime` behaving differently on BSD and MasOS. Probably the simplest thing to do would be to not run the `formatTime` tests on non-GNU platforms.

**Comment by Bodigrim** [comment]
Yeah, it seems to be because of Glibc extensions (see https://man7.org/linux/man-pages/man3/strftime.3.html#NOTES) unsupported by BSD platforms. 

(BTW I can raise a PR with these GitHub Actions, if you wish, or feel free to cherry-pick them yourself)

**Comment by AshleyYakeley** [comment]
Sure, make a PR for the GH Actions. Thanks!

**Comment by AshleyYakeley** [comment]
Fixed!
