### ISSUE TITLE
Add an Eq instance for ZonedTime

### ISSUE THREAD

**Issue by jmillikin** [haskell/time#16]
ZonedTime is (LocalTime, TimeZone) and both of those have Eq, so this should be a simple matter of adding a deriving entry.

**Comment by saurabhnanda** [comment]
> It must have a type signature like zonedTimesEquivalent :: ZonedTime -> ZonedTime -> IO Bool

Does anyone know how does a mature date/time library in any other language [1] handle this issue? Did I understand this correctly:

* Checking if two ZonedTimes with the **same TZ** are equal is not a problem, right? Even if they are far-out in the future, any changes in the TZ offset will affect both equally.
* The problem is with checking equality for two ZonedTimes with **different TZ**, because of two reasons:
  * If they are in the far future where DST adjustments are yet to happen, we cant really be sure of the equality
  * Even if we assume that we know all the relevant DST adjustments, the equality function would need to lookup a DST table, which would change the function from pure to IO.

[1] especially Java/C#- because they would be getting used by banks and financial institutions

**Comment by unhammer** [comment]
Since this is obviously something people wonder about and look for (three closed issues already), could we have a note in the doc's saying why there is no Eq instance? I was a bit surprised myself when I tried `z == z'` and got no Eq instance, and went to double-check the docs, and saw nothing, and only after pestering `#haskell` understood that some people might want `2018-11-30T01:00 UTC` to equal `2018-11-30T02:00 CET`. 

Someone else can probably phrase this better, but something like:
```
ZonedTime does not have an Eq instance, since there are multiple obvious interpretations of equality; e.g. two ZonedTime's may be considered equal if they are the same LocalTime and the same TimeZone, or we could consider them equal if they convert to the same UTCTime (even if they are in different TimeZone's).
```

**Comment by AshleyYakeley** [comment]
Yes, I think that would be a good idea.

**Comment by AshleyYakeley** [comment]
OK, this is #109.
