### ISSUE TITLE
Why the major version bump for v1.13?

### ISSUE THREAD

**Issue by sjakobi** [haskell/time#181]
The [changelog](https://hackage.haskell.org/package/time-1.13/changelog) doesn't indicate any breaking changes. Why didn't you go with 1.12.1 for the version number?

**Comment by AshleyYakeley** [comment]
I probably could have. Is it causing you problems?

**Comment by phadej** [comment]
I made a revision to blacklist it completely, https://hackage.haskell.org/package/time-1.13/revisions/

So that if someone relies on `time-1.12.1` features bounds like `time >=1.12.2 && <1.15` won't cause problems where `1.12.2` adds something which isn't in `time-1.13`.

I.e. now it looks like `time-1.13` never happened, there is no way to have it in the install plan.
