### ISSUE TITLE
TH Lift instances for time types

### ISSUE THREAD

**Issue by kokobd** [haskell/time#233]
Can we provide instances of `Language.Haskell.TH.Syntax.Lift` for types in `time`, like `UTCTime`, `DiffTime`, etc, so that time can be used in TH splices.
If there aren't major blockers (should `time` depend on `template-haskell`?), I'll be happy to submit a PR.

**Comment by AshleyYakeley** [comment]
Probably better to put them in the `template-haskell` package? I'm not sure, though.

**Comment by JackKelly-Bellroy** [comment]
My gut instinct is that `template-haskell` is a domain-independent library, and so it seems weirder to for users of `template-haskell` to depend on `time` than vice-versa. `template-haskell` seems pretty locked to specific GHC releases, whereas adding new instances to `time` should be a bit easier to publish? (Sadly, `th-compat` will be unusable here due to dep footprint, so we'll probably have to CPP it like [`time-qq`](https://github.com/christian-marie/time-qq/blob/415aaa37a0a75e91d8604eeafe6cda527fb6b4e8/lib/Data/Time/QQ.hs#L116-L156) does.)

**Comment by AshleyYakeley** [comment]
Can we use `DeriveLift`?

**Comment by JackKelly-Bellroy** [comment]
https://github.com/brendanhay/amazonka/pull/677/files

Looks like it, for everything except `DiffTime`, which does not export its constructor.

**Comment by AshleyYakeley** [comment]
OK, checking with the CLC to see in case there's a problem with `time` depending on `template-haskell`.

**Comment by AshleyYakeley** [comment]
I think the dependency is OK. However, there may not be `instance Lift Fixed`, which should be added to `template-haskell`.

**Comment by kokobd** [comment]
I've raised an issue in `template-haskell`: https://gitlab.haskell.org/ghc/ghc/-/issues/22953.
I think we can first release a version without relying on `instance Lift Fixed`. Instead, manually implement `Lift` for `DiffTime` using `diffTimeToPicoseconds`. This also makes `time` compatible with older versions of `template-haskell`.

**Comment by JackKelly-Bellroy** [comment]
The primary problem with lifting `DiffTime` is that it doesn't export its contstructor. The way Amazonka works around it is to call `fromEnum`, lift that, then call `toEnum`. Seems to work fine.
