### ISSUE TITLE
Switch from String to Text

### ISSUE THREAD

**Issue by k0ral** [haskell/time#30]
I'm willing to submit a pull request to replace all `String`s with `Text`s, will you accept it ?

**Comment by hvr** [comment]
Wouldn't that add `text` as a dependency to `time`?

**Comment by k0ral** [comment]
Sure, is that a problem ?

**Comment by hvr** [comment]
Well, it would have some ramifications, since GHC has `time` as a core/boot-package, and this would require GHC to also bundle a version of `text` (which would then get exposed via the global pkg db). I'm just pointing it out. But  I guess the major issue would be that the API of `time` would change in a non-backward compat way, which given `time`s status as a core library cause major ripples through the ecosystem.

**Comment by k0ral** [comment]
Using the [`TextualMonoid`][1] class, it is possible to do an almost backward-compatible change such that the API would accept any of `String`, lazy `Text` and strict `Text`. But that would require yet another dependency (`monoid-subclasses`)...
Another solution would be to create a distinct package to include those changes without impacting GHC, but that would lead to a lot of code duplication.
What do you think ?

[1]: https://hackage.haskell.org/package/monoid-subclasses/docs/Data-Monoid-Textual.html

**Comment by hsenag** [comment]
What's the motivation for changing - is time performance-sensitive in practice?

**Comment by k0ral** [comment]
When using `time` in a project that (rightfully) uses `Text` everywhere, one has to pack/unpack repeatedly. I'm not concerned about the performance impact (should I ?), but it feels wrong being punished by the unnecessary boilerplate, just because I cared about using the right string implementation.
I believe `time` should make using `Text` the path of least resistance.

I hope I didn't make it sound like it is a petty matter :) .

**Comment by AshleyYakeley** [comment]
I think not for time 1.*, because it's too big a change and it would have ramifications for GHC.
