### ISSUE TITLE
1.6 on Hackage is missing Haddock doc links

### ISSUE THREAD

**Issue by FranklinChen** [haskell/time#43]
http://hackage.haskell.org/package/time-1.6 is missing Haddock doc links.

**Comment by AshleyYakeley** [comment]
That's because it hasn't built yet.

**Comment by AshleyYakeley** [comment]
@hvr why hasn't Hackage built time-1.6 yet?
http://hackage.haskell.org/package/time-1.6/reports/

**Comment by hvr** [comment]
@davean do you know what's up with the doc builders?

**Comment by davean** [comment]
The issue was:

Resolving dependencies...
cabal: Could not resolve dependencies:
next goal: time (user goal)
rejecting: time-1.5.0.1, 1.5, 1.4.2, 1.4.1, 1.4.0.2, 1.4.0.1, 1.4, 1.3,
1.2.0.5, 1.2.0.4, 1.2.0.3, 1.2.0.2, 1.2.0.1, 1.2, 1.1.4, 1.1.3, 1.1.2.4,
1.1.2.3, 1.1.2.2, 1.1.2.1, 1.1.2.0, 1.0 (global constraint requires ==1.6)
Dependency tree exhaustively searched.

but I've forced it to build now. A major improvement to the doc builder
would be to make it actually report dependency failures.

**Comment by AshleyYakeley** [comment]
Thanks. Doc links are there now.
