### ISSUE TITLE
Show instance for UTCTime

### ISSUE THREAD

**Issue by ozgurakgun** [haskell/time#7]
In short: the Show instance for UTCTime doesn't come into scope when `Data.Time.Clock` is imported. The haddocks claim that it will. This is confusing.

The haddocks for UTCTime claim the existence of a Show instance: http://hackage.haskell.org/package/time-1.5/docs/Data-Time-Clock.html

And indeed I was using `getCurrentTime >>= print` in a piece of code and it was working.

Then the following happened.

```
$ ghci
GHCi, version 7.8.3: http://www.haskell.org/ghc/  :? for help
Loading package ghc-prim ... linking ... done.
Loading package integer-gmp ... linking ... done.
Loading package base ... linking ... done.
Prelude> import Data.Time.Clock
Prelude Data.Time.Clock> getCurrentTime >>= print

<interactive>:3:20:
    No instance for (Show UTCTime) arising from a use of ‘print’
    In the second argument of ‘(>>=)’, namely ‘print’
    In the expression: getCurrentTime >>= print
    In an equation for ‘it’: it = getCurrentTime >>= print
```

Then I checked my old code which worked. It has a bunch of seemingly unrelated imports. A few minutes of uncommenting the imports one by one, I noticed when I import `System.Directory` the Show instance comes into scope.

```
$ ghci
GHCi, version 7.8.3: http://www.haskell.org/ghc/  :? for help
Loading package ghc-prim ... linking ... done.
Loading package integer-gmp ... linking ... done.
Loading package base ... linking ... done.
Prelude> import Data.Time.Clock
Prelude Data.Time.Clock> import System.Directory ()
Prelude Data.Time.Clock System.Directory> getCurrentTime >>= print
Loading package array-0.5.0.0 ... linking ... done.
Loading package deepseq-1.3.0.2 ... linking ... done.
Loading package old-locale-1.0.0.6 ... linking ... done.
Loading package time-1.4.2 ... linking ... done.
2014-10-22 09:07:14.838338 UTC
```

It seems this instance is defined in `Data.Time.LocalTime.LocalTime`.

```
Prelude Data.Time.Clock System.Directory> :i UTCTime
data UTCTime
  = UTCTime {utctDay :: time-1.4.2:Data.Time.Calendar.Days.Day,
             utctDayTime :: DiffTime}
  	-- Defined in ‘time-1.4.2:Data.Time.Clock.UTC’
instance Eq UTCTime -- Defined in ‘time-1.4.2:Data.Time.Clock.UTC’
instance Ord UTCTime -- Defined in ‘time-1.4.2:Data.Time.Clock.UTC’
instance Read UTCTime
  -- Defined in ‘time-1.4.2:Data.Time.Format.Parse’
instance Show UTCTime
  -- Defined in ‘time-1.4.2:Data.Time.LocalTime.LocalTime’
```

The orphan instance can be seen from: http://hackage.haskell.org/package/time-1.5/docs/src/Data-Time-LocalTime-LocalTime.html

Moving the instance back to `Data.Time.Clock` probably creates cyclic imports. There must be a solution involving a few internal modules, I suppose.

In any case the haddocks are definitely misleading.

(I now I have used time-1.4.2 above, but the same problem exists in time-1.5 too)

**Comment by tonymorris** [comment]
Orphan instances do not belong. Correcting documentation is not an acceptable consolation.

**Comment by AshleyYakeley** [comment]
I'm of the opinion that orphan instances are a lot less harmful than some people suppose, particularly when the class, the type, and the instance are all in the same package.

The orphan instance problem happens when there is more than one instance for a given class and type. This is much more likely to happen when it isn't clear which instance is the "proper" one, or if the authors of the instances aren't aware of each other's code. This seems unlikely in this case: clearly the instance defined in the package is the proper one.

And the only actual effect of the problem is that Haskell will use whichever instance is in scope, or reject the program if they both are. This is not particularly bad behaviour. I would describe it as, at worst, *slightly awkward*.

**Comment by ozgurakgun** [comment]
@AshleyYakeley can you please respond to the original problem, and see if you don't think that's a problem any more?

Just to clarify: UTCTime reports to have a Show instance available in the documentation of Data.Time.Clock, but loading that module into ghci doesn't bring the claimed instance into scope.

**Comment by ozgurakgun** [comment]
Oh, I had missed the previous documentation update. I can live with this. Though it is a shame the problem wasn't "properly" solved by either bringing the instance into scope or not listing the instance in the documentation at all.

**Comment by tomjaguarpaw** [comment]
The package author does not have a choice to omit it from documentation, as far as I know.  That is determined by Haddock.

**Comment by ozgurakgun** [comment]
@tomjaguarpaw so maybe this can be regarded as a bug of Haddock. It probably should only list the instances that are in scope for a given module.

**Comment by hvr** [comment]
@ozgurakgun the problem is though, if Haddock showed only the locally visible instances for modules which expose a data-type, you'd have a hard time figuring out which instances exist at all

**Comment by AshleyYakeley** [comment]
Right, it's two separate things: "instances defined in this module" and "instances for this type or class". The former is part of the contents of the module, the latter is more "see also". But I think Haddock only shows the latter.

**Comment by gbaz** [comment]
Current Haskell culture really discourages orphan instances. So that makes this behaviour _highly surprising_ even with the documentation.

Would you be open to a patch if someone else jumped in to help?

**Comment by AshleyYakeley** [comment]
No.

**Comment by gbaz** [comment]
Why?

**Comment by AshleyYakeley** [comment]
@gbaz, I'm of the opinion that orphan instances are a lot less harmful than some people suppose, particularly when the type (or the class) and the instance are in the same package.

The orphan instance problem happens when there is more than one instance for a given class and type. This is much more likely to happen when it isn't clear which instance is the "proper" one, or if the authors of the instances aren't aware of each other's code. This seems unlikely in this case: clearly the instance defined in the package is the proper one.

And the only actual effect of the problem is that Haskell will use whichever instance is in scope, or reject the program if they both are. This is not particularly bad behaviour. I would describe it as, at worst, *slightly awkward*.

**Comment by gbaz** [comment]
Ok. I understand the confusion. You are responding with a defense of this orphan as not bad because it will not lead to duplication of instances. There I completely agree!

However, what we have is a different problem -- one that leads to confusion in using the library, which is that it is possible to bring the datatype into scope without its attendant instances. This behavior is confusing to end-users, as the ticket demonstrates (and I've run into the same thing in the past, as I know others have). I'm not supporting this change because of a moral position on orphans internal to a library -- I'm supporting it because it is a far nicer experience for end-users to have instances for things like Show arrive along with attendant datatypes instead of them needing to import said instances from elsewhere.

If, "behind the scenes" there were an internal module that had the type, and another with instances on the type, but in the public interface, pulling in the module with the type also pulled in the instances, for example, I would find that fine too.

Does that help clear up the concern?

**Comment by erikd** [comment]
@gbaz :+1:

**Comment by afcowie** [comment]
@gbaz +1

**Comment by bitemyapp** [comment]
@gbaz :+1:

**Comment by tomjaguarpaw** [comment]
@gbaz :+1:

**Comment by relrod** [comment]
@gbaz :+1:

**Comment by ekmett** [comment]
I agree with Gershom that being able to get the data type and not the instance through the public API of the package without going through a module that is clearly flagged as "evil and internal" is confusing.

It isn't like the user can just make local decisions on the right instance here, unless they happen to also know that they aren't using _any other code_ transitively that also happens to make that decision one way or another. 

This isn't really a locally decidable affair.

**Comment by mwotton** [comment]
@gbaz :+1:

**Comment by jpvillaisaza** [comment]
@gbaz Is your idea of a behind the scenes solution (see https://github.com/haskell/time/issues/7#issuecomment-74741729) similar to what the `Data.Time` module does? It exports everything, so if you import that one you get both the `getCurrentTime` function and `Show` instance for `UTCTime` for example. I don't know if that's a complete solution (you can install import `Data.Time.Clock` and still not get the instance, it only works if you import `Data.Time` or both `Data.Time.Clock` and `Data.Time.Format`), but that module could help with your idea.

I'm also not sure if this issue should be closed. Now there's a new issue with the problem (https://github.com/haskell/time/issues/25).
